Repository CONTENIDO/CONTENIDO, pull requests merged in 2019-12, with the labels that each got.

#94 #93 Rendering cHTMLRadiobutton & cHTMLCheckbox with label requires an id attribute.
  contenido/classes/html/class.html.checkbox.php
  contenido/classes/html/class.html.radiobutton.php
  setup/lib/class.setupcontrols.php
  setup/steps/forms/clientmode.php
  setup/steps/forms/configmode.php
  setup/templates/setup/forms/clientmode.tpl
  setup/templates/setup/forms/configmode.tpl
  setup/templates/setup/forms/configmodewopass.tpl
  test/contenido/html/cHtmlCheckBoxTest.php
  test/contenido/html/cHtmlRadioButtonTest.php
Labels: bug

#95 #27 Invalid entries in "con_user" table after update from 4.8.
  setup/data/sysadmin/sysadmin1.sql
  setup/lib/functions.sql.php
  setup/upgrade_jobs/class.upgrade.job.main.php
Labels: bug

#97 refactored cValidatorEmail and its test
  contenido/classes/validator/class.validator.abstract.php
  contenido/classes/validator/class.validator.email.php
  contenido/classes/validator/class.validator.factory.php
  test/contenido/validator/cValidatorEmailTest.php
Labels: improvement

#99 Bug/#28 tab navigation in modules area contains entries of previous loaded module
  contenido/includes/include.lay_new.php
  contenido/includes/include.mod_new.php
  contenido/includes/include.tpl_new.php
Labels: bug

#103 Task/#102 move registration of row mark mouse event handler to rowmark.js
  contenido/backend_search.php
  contenido/classes/gui/class.menu.php
  contenido/includes/functions.stat.php
  contenido/includes/include.con_art_overview.php
  contenido/includes/include.rights_menu.php
  contenido/plugins/content_allocation/templates/template.tree_article.html
  contenido/plugins/content_allocation/templates/template.tree_structure.html
  contenido/plugins/cronjobs_overview/templates/left_bottom.html
  contenido/plugins/cronjobs_overview/templates/right_bottom_crontab_edit.html
  contenido/plugins/cronjobs_overview/templates/right_bottom_overview.html
  contenido/plugins/linkchecker/templates/standard/template.linkchecker_test.html
  contenido/plugins/linkchecker/templates/standard/template.linkchecker_test_errors.html
  contenido/plugins/linkchecker/templates/standard/template.linkchecker_test_errors_cat.html
  contenido/plugins/linkchecker/templates/standard/template.linkchecker_whitelist.html
  contenido/plugins/linkchecker/templates/standard/template.linkchecker_whitelist_urls.html
  contenido/plugins/newsletter/templates/standard/template.newsletter_left_top.html
  contenido/plugins/user_forum/templates/template.left_bottom.html
  contenido/plugins/user_forum/templates/template.right_bottom.html
  contenido/plugins/workflow/templates/template.workflow_tasks.html
  contenido/scripts/rowMark.js
  contenido/templates/standard/header.html
  contenido/templates/standard/template.backend_search_results.html
  contenido/templates/standard/template.client_edit.html
  contenido/templates/standard/template.client_menu.html
  contenido/templates/standard/template.con_art_overview.html
  contenido/templates/standard/template.con_str_overview.html
  contenido/templates/standard/template.con_subnav.html
  contenido/templates/standard/template.files_overview.html
  contenido/templates/standard/template.generic_file_overview.html
  contenido/templates/standard/template.generic_page.html
  contenido/templates/standard/template.generic_page_html5.html
  contenido/templates/standard/template.grouprights_create.html
  contenido/templates/standard/template.grouprights_details.html
  contenido/templates/standard/template.grouprights_memberlist.html
  contenido/templates/standard/template.grouprights_memberselect.html
  contenido/templates/standard/template.grouprights_menu.html
  contenido/templates/standard/template.grouprights_overview.html
  contenido/templates/standard/template.lang_overview.html
  contenido/templates/standard/template.lay_overview.html
  contenido/templates/standard/template.log_main.html
  contenido/templates/standard/template.log_menu.html
  contenido/templates/standard/template.mycontenido_lastarticles.html
  contenido/templates/standard/template.mycontenido_settings.html
  contenido/templates/standard/template.mycontenido_start.html
  contenido/templates/standard/template.rights.html
  contenido/templates/standard/template.rights_create.html
  contenido/templates/standard/template.rights_overview.html
  contenido/templates/standard/template.stat_menu.html
  contenido/templates/standard/template.stat_overview.html
  contenido/templates/standard/template.stat_search_menu.html
  contenido/templates/standard/template.stat_top.html
  contenido/templates/standard/template.str_overview.html
  contenido/templates/standard/template.tpl_overview.html
  contenido/templates/standard/template.upl_dirs_overview.html
Labels: enhancement, improvement

#98 #33 Con.Loader calls callback twice.
  contenido/scripts/general.js
Labels: bug

#105 #104 Implement autofill feature for password fields.
  contenido/classes/html/class.html.formelement.php
  contenido/classes/html/class.html.passwordbox.php
  contenido/includes/include.frontend.user_edit.php
  contenido/includes/include.mycontenido_settings.php
  contenido/includes/include.rights_create.php
  contenido/includes/include.rights_overview.php
  contenido/includes/include.system_configuration.php
  contenido/plugins/siwecos/templates/template.right_bottom.tpl
  test/contenido/html/cHtmlPasswordBoxTest.php
  test/lib/class.testing.test.case.php
Labels: bug

#110 #109 JavaScript error "Uncaught TypeError: contentWindow.$ is not a f…
  contenido/scripts/general.js
Labels: bug

#112 #111 Remove old deprecated functions in unit tests.
  test/chains/ContenidoContentCopyArticle.php
  test/chains/ContenidoContentDeleteArticle.php
  test/chains/ExampleContenidoChainExecuteObject.php
  test/chains/ExampleContenidoChainExecuteStaticMethod.php
  test/contenido/classes/cApiCecRegistry.php
Labels: enhancement

#117 #116 Prevent possible XML errors in cUpgradeJob_0005
  setup/upgrade_jobs/class.upgrade.job.0005.php
Labels: bug
