Repository CONTENIDO/CONTENIDO, pull requests merged in 2023-02, with the labels that each got.

#300 #299 Document namespace usage in cAutoload class.
  contenido/classes/class.autoload.php
Labels: documentation

#271 Add page title to search index
  contenido/classes/class.array.php
  contenido/classes/search/class.search.index.php
Labels: enhancement

#269 Change fallback similartiy from 0 to 0.0001
  contenido/classes/search/class.search.result.php
Labels: bug

#270 Search: Fix matching for Umlaute
  contenido/classes/search/class.search.result.php
Labels: bug

#306 switched to short array syntax in contenido/cronjobs
  contenido/cronjobs/send_reminder.php
Labels: enhancement

#307 switched to short array syntax in contenido/external
  contenido/external/codemirror/class.codemirror.php
  contenido/external/frontend/dbfs.php
  contenido/external/wysiwyg/tinymce3/editorclass.php
  contenido/external/wysiwyg/tinymce4/contenido/ajax/class.tinymce_list.php
Labels: enhancement

#308 switched to short array syntax in contenido/includes/functions*
  contenido/includes/api/functions.frontend.list.php
  contenido/includes/functions.con2.php
  contenido/includes/functions.database.php
  contenido/includes/functions.encoding.php
  contenido/includes/functions.file.php
  contenido/includes/functions.i18n.php
  contenido/includes/functions.lang.php
  contenido/includes/functions.pathresolver.php
  contenido/includes/functions.str.php
  contenido/includes/functions.tpl.php
  contenido/includes/functions.upl.php
Labels: enhancement

#310 switched to short array syntax in remaining files in contenido/includes
  contenido/includes/ajax/include.ajax.con.php
  contenido/includes/chains/include.chain.frontend.cat_backendaccess.php
  contenido/includes/chains/include.chain.template.parsetemplate.php
  contenido/includes/frontend/include.front_crcloginform.inc.php
  contenido/includes/globals_off.inc.php
  contenido/includes/include.con_str_overview.php
  contenido/includes/include.default_subnav.php
  contenido/includes/include.grouprights_con.php
  contenido/includes/include.grouprights_members.php
  contenido/includes/include.grouprights_str.php
  contenido/includes/include.html_tpl_history.php
  contenido/includes/include.js_history.php
  contenido/includes/include.mail_log.php
  contenido/includes/include.mycontenido.tasks.edit.php
  contenido/includes/include.mycontenido.tasks.php
  contenido/includes/include.mycontenido_lastarticles.php
  contenido/includes/include.note.popup.php
  contenido/includes/include.style_history.php
  contenido/includes/include.system_log_sysvalues.php
  contenido/includes/include.todo.popup.php
  contenido/includes/include.upl_dirs_overview.php
  contenido/includes/include.upl_edit.php
  contenido/includes/pseudo-cron.inc.php
  contenido/includes/type/action/include.str_movesubtree.action.php
  contenido/includes/type/action/include.str_newcat.action.php
  contenido/includes/type/action/include.str_newtree.action.php
  contenido/includes/type/action/include.str_renamecat.action.php
Labels: enhancement

#311 require ext-dom
  composer.json
Labels: enhancement

#314 Bug/57 articles overview handle large amount of pages
  contenido/classes/class.article.overview.helper.php
  contenido/includes/include.con_art_overview.php
  data/config/production/config.autoloader.php
Labels: bug

#313 #281 Fix thrown PHP Warnings.
  contenido/ajaxmain.php
  contenido/includes/functions.general.php
  contenido/main.php
Labels: bug

#235 Allow combined words in search index
  contenido/classes/search/class.search.index.php
Labels: bug

#316 switched to short array syntax in remaining files in folder contenido
  contenido/frameset.php
  contenido/frameset_left.php
  contenido/frameset_right.php
  contenido/logout.php
  contenido/scripts/articleObject.js.php
  contenido/scripts/iZoom.js.php
Labels: enhancement

#320 Bug/#281 fix thrown php warnings
  contenido/classes/auth/class.auth.handler.backend.php
  contenido/classes/contenido/class.module.php
  contenido/classes/content_types/class.content.type.abstract.php
  contenido/classes/content_types/class.content.type.date.php
  contenido/includes/include.con_left_top.php
  contenido/includes/include.con_str_overview.php
  contenido/includes/include.frontend.left_top.php
  contenido/includes/include.html_tpl_edit_form.php
  contenido/includes/include.html_tpl_files_overview.php
  contenido/includes/include.html_tpl_left_top.php
  contenido/includes/include.js_edit_form.php
  contenido/includes/include.js_files_overview.php
  contenido/includes/include.js_left_top.php
  contenido/includes/include.lay_new.php
  contenido/includes/include.mod_new.php
  contenido/includes/include.mod_overview.php
  contenido/includes/include.mycontenido.php
  contenido/includes/include.rights_left_top.php
  contenido/includes/include.rights_menu.php
  contenido/includes/include.style_edit_form.php
  contenido/includes/include.style_files_overview.php
  contenido/includes/include.style_left_top.php
  contenido/includes/include.tpl_new.php
  contenido/plugins/pim/classes/setup/class.pimpluginsetup.install.php
Labels: bug

#319 removed md5.js
  contenido/scripts/md5.js
Labels: enhancement

#321 #317 Plugin installation on a blank CONTENIDO.
  contenido/plugins/pim/includes/include.right_bottom.php
Labels: bug

#322 #66 Broken notifications for frozen articles
  contenido/includes/include.con_content_list.php
  contenido/includes/include.con_edit_form.php
  contenido/plugins/content_allocation/includes/include.contentallocation_article.php
Labels: bug

#318 switched to short array syntax in remaining files in request validato…
  contenido/classes/class.requestvalidator.php
  contenido/classes/class.security.php
  data/config/production/config.http_check.php
  data/config/test/config.http_check.php
Labels: enhancement

#323 #38 cAuth calls abstract methods of cAuthHandlerAbstract
  contenido/classes/auth/class.auth.handler.abstract.php
  contenido/classes/auth/class.auth.handler.backend.php
  contenido/classes/auth/class.auth.handler.frontend.php
  contenido/classes/auth/class.auth.php
  contenido/classes/class.array.php
  contenido/classes/class.registry.php
Labels: enhancement

#324 Bug/57 articles overview handle large amount of pages
  contenido/classes/class.article.overview.helper.php
Labels: bug

#326 Feature/325 refactor generation of dynamic content type view code
  contenido/classes/content_types/class.content.type.abstract.php
  contenido/classes/content_types/class.content.type.filelist.php
  contenido/classes/content_types/class.content.type.teaser.php
  contenido/plugins/form_assistant/classes/class.content.type.pifa_form.php
  contenido/plugins/user_forum/classes/class.content.type.user_forum.php
  test/contenido/content_types/cContentTypeAbstractTest.php
Labels: enhancement

#328 #327 New functions for ItemCollection to add/remove multiple result f…
  contenido/classes/genericdb/class.item.collection.php
  test/contenido/genericdb/ItemCollectionTest.php
Labels: enhancement

#330 #329 Optimize class cModuleFileTranslation.
  contenido/classes/module/class.module.filetranslation.php
Labels: enhancement

#334 Task/331 optimize the usage of the class cmodulehandler
  composer.json
  contenido/classes/contenido/class.layout.php
  contenido/classes/contenido/class.module.php
  contenido/classes/module/class.module.filetranslation.php
  contenido/classes/module/class.module.handler.php
  contenido/classes/module/class.module.template.handler.php
  contenido/includes/functions.mod.php
  contenido/includes/include.con_translate.php
  contenido/includes/include.mod_edit_form.php
  contenido/styles/contenido.css
  contenido/templates/standard/template.mod_edit_form.html
Labels: enhancement

#332 required ext-gd e.g. for use in functions.api.images.php
  composer.json
Labels: enhancement

#333 switched to short array syntax in example modules
  setup/data/examples/data/modules/config_social_media/php/config_social_media_output.php
  setup/data/examples/data/modules/content_link_list/php/content_link_list_output.php
  setup/data/examples/data/modules/content_map_google/php/content_map_google_output.php
  setup/data/examples/data/modules/content_search_results/php/content_search_results_output.php
  setup/data/examples/data/modules/content_sitemap_xml/php/content_sitemap_xml_input.php
  setup/data/examples/data/modules/form_newsletter_subscription/php/form_newsletter_subscription_input.php
  setup/data/examples/data/modules/form_newsletter_subscription/php/form_newsletter_subscription_output.php
  setup/data/examples/data/modules/handler_newsletter_subscription/php/handler_newsletter_subscription_input.php
  setup/data/examples/data/modules/handler_newsletter_subscription/php/handler_newsletter_subscription_output.php
  setup/data/examples/data/modules/head_title/php/head_title_output.php
  setup/data/examples/data/modules/navigation_bottom/php/navigation_bottom_output.php
  setup/data/examples/data/modules/navigation_breadcrumb/php/navigation_breadcrumb_output.php
  setup/data/examples/data/modules/navigation_lang_changer/php/navigation_lang_changer_output.php
  setup/data/examples/data/modules/navigation_searchform_top/php/navigation_searchform_top_output.php
  setup/data/examples/data/modules/navigation_social_media/php/navigation_social_media_output.php
  setup/data/examples/data/modules/script_fb_sdk/php/script_fb_sdk_output.php
Labels: enhancement

#335 #242 No upload directory is set in CMS_IMGEDITOR on load.
  contenido/classes/content_types/class.content.type.imgeditor.php
  contenido/scripts/content_types/cmsImgeditor.js
Labels: bug

#337 #336 Optimize the cArticleCollector class
  contenido/classes/class.article.collector.php
  contenido/classes/genericdb/class.item.collection.php
  contenido/classes/genericdb/trait.item.collection.chunk.php
  data/config/production/config.autoloader.php
Labels: enhancement

#338 switched to short array syntax in remaining setup files
  setup/data/examples/concache.php
  setup/lib/class.setupcontrols.php
  setup/lib/functions.sql.php
  setup/lib/functions.system.php
  setup/lib/include.db.controller.php
  setup/steps/forms/clientadjust.php
  setup/steps/forms/clientmode.php
  setup/steps/forms/pathinfo.php
  setup/steps/languagechooser.php
  setup/upgrade_jobs/class.upgrade.job.0004.php
  setup/upgrade_jobs/class.upgrade.job.0006.php
  setup/upgrade_jobs/class.upgrade.job.0007.php
  setup/upgrade_jobs/class.upgrade.job.abstract.php
  setup/upgrade_jobs/class.upgrade.job.main.php
Labels: enhancement

#339 switched to short array syntax in data/config
  data/config/production/config.autoloader.php
  data/config/production/config.misc.php
  data/config/production/config.path.php
  data/config/test/config.autoloader.php
  data/config/test/config.misc.php
  data/config/test/config.path.php
Labels: enhancement

#341 Task/61 performance issues on systems with many articles
  contenido/backend_search.php
  contenido/classes/class.article.overview.helper.php
  contenido/classes/class.backend.search.helper.php
  contenido/classes/class.date.php
  contenido/includes/functions.general.php
  contenido/includes/include.con_left_top.php
  contenido/scripts/general.js
  contenido/styles/contenido.css
  contenido/templates/standard/template.backend_search_results.html
  contenido/templates/standard/template.con_left_top.html
  contenido/templates/standard/template.con_left_top_art_search.html
  contenido/templates/standard/template.con_left_top_cat_edit.html
  contenido/templates/standard/template.con_left_top_sync.html
  contenido/tools/mpAutoloaderClassMap/mpClassTypeFinder.php
  contenido/xml/legend.xml
  contenido/xml/navigation.xml
  contenido/xml/system.xml
  data/config/production/config.autoloader.php
  data/config/test/config.autoloader.php
  data/config/test/config.misc.php
  test/contenido/classes/cDateTest.php
Labels: enhancement

#344 #343 cDebugFile issue with initial writing into debug.log.
  contenido/classes/debug/class.debug.file.php
Labels: bug

#346 #342 Compatibility with PHP 8.1.
  contenido/classes/class.permission.php
Labels: enhancement

#347 Task: Deprecated date functions.
  contenido/includes/include.frontend.user_edit.php
  contenido/includes/include.mycontenido.php
  contenido/includes/include.stat_menu.php
  contenido/includes/include.stat_overview.php
  contenido/includes/include.upl_edit.php
  contenido/plugins/newsletter/includes/include.newsletter_edit.php
  contenido/plugins/workflow/includes/include.workflow_edit.php
  test/contenido/classes/cDateTest.php
  test/contenido/includes/cFunctionsGeneralTest.php
Labels: enhancement

#352 #350 PIM: Enhance plugin functionality
  contenido/plugins/pim/xml/plugin_info.xml
Labels: enhancement

#353 Task/342 compatibility with php 81
  contenido/classes/class.date.php
  contenido/classes/content_types/class.content.type.date.php
  contenido/plugins/linkchecker/includes/include.linkchecker.php
  contenido/plugins/linkchecker/includes/include.linkchecker_whitelist.php
  contenido/plugins/newsletter/classes/class.newsletter.jobs.php
  contenido/plugins/newsletter/classes/class.newsletter.php
  test/contenido/classes/cDateTest.php
Labels: enhancement

#354 Enhanced performance of `cRegistry::getEncoding()` by storing encodin…
  contenido/classes/class.registry.php
Labels: enhancement

#356 Line feed
  contenido/includes/frontend/include.front_content.php
Labels: enhancement

#358 #357 PIM: Better error handling for uploaded invalid plugin archives
  contenido/includes/functions.general.php
  contenido/plugins/pim/classes/setup/class.pimpluginsetup.php
  contenido/plugins/pim/classes/util/zip/class.pimpluginarchiveextractor.php
  contenido/plugins/pim/includes/include.right_bottom.php
  contenido/plugins/pim/locale/de_DE/LC_MESSAGES/pim.mo
  contenido/plugins/pim/locale/de_DE/LC_MESSAGES/pim.po
  contenido/plugins/pim/locale/pim.pot
  contenido/scripts/jquery/plugins/tipsy.js
Labels: enhancement

#361 Reworked password reset functionality for the backend login, moved so…
  contenido/classes/class.password.request.php
  contenido/classes/contenido/class.user.passwordrequest.php
  contenido/classes/contenido/class.user.php
  contenido/cronjobs/maintain_password_reset_requests.php
Labels: enhancement

#365 #364 Module synchronization generates warnings.
  contenido/classes/contenido/class.module.php
  contenido/classes/genericdb/class.item.php
  contenido/classes/module/class.module.handler.php
  contenido/classes/module/class.module.synchronizer.php
  contenido/includes/include.mod_edit_form.php
Labels: bug
